# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cct < Formula
  desc "Browse, search, and manage Claude Code session history from the terminal"
  homepage "https://github.com/andyhtran/cct"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andyhtran/cct/releases/download/v1.7.0/cct_Darwin_x86_64.tar.gz"
      sha256 "da3f585411f8d752c947eed0c517987fca152f00d81ef085035643ed9f8cceee"

      define_method(:install) do
        bin.install "cct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andyhtran/cct/releases/download/v1.7.0/cct_Darwin_arm64.tar.gz"
      sha256 "d13252fe823c10c92ca71c73f490c79cbd535613223d28059a426d642fd91c1c"

      define_method(:install) do
        bin.install "cct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andyhtran/cct/releases/download/v1.7.0/cct_Linux_x86_64.tar.gz"
      sha256 "636befbabdf0ec9656502f87c8a5d22d6f14d90d330a255d8f2dd393b907baed"
      define_method(:install) do
        bin.install "cct"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andyhtran/cct/releases/download/v1.7.0/cct_Linux_arm64.tar.gz"
      sha256 "a5274841a850b9ff9718ed1d559d5f9d960f210325308172109eefbb81a04d0b"
      define_method(:install) do
        bin.install "cct"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cct version")
  end
end
