# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cct < Formula
  desc "Browse, search, and manage Claude Code session history from the terminal"
  homepage "https://github.com/andyhtran/cct"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andyhtran/cct/releases/download/v0.5.0/cct_Darwin_x86_64.tar.gz"
      sha256 "7332fca48225e77af1591872fa3bdb45a35b76430640c588a44ec79ccfd37eef"

      define_method(:install) do
        bin.install "cct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andyhtran/cct/releases/download/v0.5.0/cct_Darwin_arm64.tar.gz"
      sha256 "1f20dc395e602c67fa79d31fd9bebfe77991f0aeefcee2e949be8001cb2469df"

      define_method(:install) do
        bin.install "cct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andyhtran/cct/releases/download/v0.5.0/cct_Linux_x86_64.tar.gz"
      sha256 "bfac097fbc3cdbaabbee0ee9be7897b02d1df32857bcd7ff1d276e8769db0dfa"
      define_method(:install) do
        bin.install "cct"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andyhtran/cct/releases/download/v0.5.0/cct_Linux_arm64.tar.gz"
      sha256 "a28a12a0112701c763a63fa480fae2d0875fe35c47d9c3b9a3a9f37226a71ff9"
      define_method(:install) do
        bin.install "cct"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/cct version")
  end
end
