# typed: false
# frozen_string_literal: true

# This file is generated by jobclip release tooling. DO NOT EDIT.
class Jobclip < Formula
  desc "Search tech jobs across popular company career pages"
  homepage "https://github.com/andyhtran/jobclip"
  version "0.2.0"
  license :cannot_represent

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andyhtran/jobclip/releases/download/v0.2.0/jobclip_0.2.0_darwin_amd64.tar.gz"
      sha256 "b54c47d9d9b0b3934aff2b12258376cd7a0326576c5b29b1d6dec4aadff9bd1a"

      define_method(:install) do
        bin.install "jobclip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andyhtran/jobclip/releases/download/v0.2.0/jobclip_0.2.0_darwin_arm64.tar.gz"
      sha256 "0455b202c305b36bf39b30fdfd8019e4662aaea2755b293272a94c2e9a966837"

      define_method(:install) do
        bin.install "jobclip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andyhtran/jobclip/releases/download/v0.2.0/jobclip_0.2.0_linux_amd64.tar.gz"
      sha256 "a8c61e61dcaa3d05068541680fd4cc77cb79cb8798f2d64ea87c6e2ae51b6445"
      define_method(:install) do
        bin.install "jobclip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andyhtran/jobclip/releases/download/v0.2.0/jobclip_0.2.0_linux_arm64.tar.gz"
      sha256 "96e7db5ccbdf8b858958e547387f52e02aa89e04794fc56df4cab09991a40d2f"
      define_method(:install) do
        bin.install "jobclip"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jobclip version")
  end
end
