# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slacky < Formula
  desc "Read-only Slack search for fast context, built for people and agents"
  homepage "https://github.com/andyhtran/slacky"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andyhtran/slacky/releases/download/v0.1.0/slacky_Darwin_x86_64.tar.gz"
      sha256 "2d8a695558ead4604d8dc47c9b49de1c68122b4cc1c7a53c84dc8cddb7a93ac6"

      define_method(:install) do
        bin.install "slacky"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andyhtran/slacky/releases/download/v0.1.0/slacky_Darwin_arm64.tar.gz"
      sha256 "80bc17306af865075c2c66a77d9b96fd9371201c1a99229fb19b13bed466f296"

      define_method(:install) do
        bin.install "slacky"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andyhtran/slacky/releases/download/v0.1.0/slacky_Linux_x86_64.tar.gz"
      sha256 "f0ceeb44bf680bd61d4fc9c4568ee34b5ddb22400f51a2162ed2b50865f0a8ec"
      define_method(:install) do
        bin.install "slacky"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andyhtran/slacky/releases/download/v0.1.0/slacky_Linux_arm64.tar.gz"
      sha256 "6d6d2c4e7856f9fb0512379a340626e64639d9578af2e2f187776aaf7649396e"
      define_method(:install) do
        bin.install "slacky"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/slacky version")
  end
end
