# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slacky < Formula
  desc "Read-only Slack search for fast context, built for people and agents"
  homepage "https://github.com/andyhtran/slacky"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/andyhtran/slacky/releases/download/v1.1.0/slacky_Darwin_x86_64.tar.gz"
      sha256 "8bd06961d9500697c2aeb1bd6e1998e23cd82dc0d3108b2c3102a00f2584b10f"

      define_method(:install) do
        bin.install "slacky"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/andyhtran/slacky/releases/download/v1.1.0/slacky_Darwin_arm64.tar.gz"
      sha256 "836608f7b14ab15a8a5e782820d12300657f4e0d37a0d1ce790e1c0ba71071cc"

      define_method(:install) do
        bin.install "slacky"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/andyhtran/slacky/releases/download/v1.1.0/slacky_Linux_x86_64.tar.gz"
      sha256 "09ef6ef7c4163007c9b0917eca60a676f29256299faf0cc1f66236130b9db9e2"
      define_method(:install) do
        bin.install "slacky"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/andyhtran/slacky/releases/download/v1.1.0/slacky_Linux_arm64.tar.gz"
      sha256 "30ad724d118ede9dd43c4bb6307f25efcdf42eb13dce6e643b2cf462f849fbd5"
      define_method(:install) do
        bin.install "slacky"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/slacky version")
  end
end
